services:
  db:
    image: postgres:18-alpine
    ports:
      - 8432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: db
    secrets:
      - db_password
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 6123:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@citizix.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_pass
    secrets:
      - pgadmin_pass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_servers:/pgadmin4/servers.json

volumes:
  postgres_vol:
  pgadmin_data:
  pgadmin_servers:

secrets:
  db_password:
    file: ./secrets/db_password
  pgadmin_pass:
    file: ./secrets/pgadmin_pass
