"""Fix FK Tables pruduct and product_group

Revision ID: 11083680c84e
Revises: b4fd7e6d6a6b
Create Date: 2025-10-04 12:21:24.972299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11083680c84e'
down_revision: Union[str, Sequence[str], None] = 'b4fd7e6d6a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_id_product_id_product_group'), 'product', type_='foreignkey')
    op.create_foreign_key('fk_id_product_id_product_group', 'product', 'product_group', ['fk_product_group'], ['id_product_group'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_id_product_id_product_group', 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_id_product_id_product_group'), 'product', 'product_group', ['id_product'], ['id_product_group'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
