"""Add Table Date Operation schema

Revision ID: 1982bc15e86e
Revises: 2c755891a3ef
Create Date: 2025-10-04 20:46:49.198869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1982bc15e86e'
down_revision: Union[str, Sequence[str], None] = '2c755891a3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_operation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата события'),
    sa.PrimaryKeyConstraint('id', name='pk_city_type_id'),
    comment='Дата операции'
    )
    op.create_index('ix_date_operation_date', 'date_operation', ['date'], unique=False)
    op.create_foreign_key('fk_facts_date_operation_id', 'facts', 'date_operation', ['fk_id_date'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_facts_date_operation_id', 'facts', type_='foreignkey')
    op.drop_index('ix_date_operation_date', table_name='date_operation')
    op.drop_table('date_operation')
    # ### end Alembic commands ###
