"""Add Table Facts

Revision ID: 2c755891a3ef
Revises: 11083680c84e
Create Date: 2025-10-04 12:54:57.423864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c755891a3ef'
down_revision: Union[str, Sequence[str], None] = '11083680c84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fk_id_city', sa.UUID(), nullable=True, comment='FK ID Город'),
    sa.Column('fk_id_customer', sa.UUID(), nullable=True, comment='FK ID Покупатель'),
    sa.Column('fk_id_product', sa.UUID(), nullable=True, comment='FK ID Продукт'),
    sa.Column('fk_id_date', sa.UUID(), nullable=True, comment='FK ID Дата'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Цена'),
    sa.Column('volume', sa.Integer(), nullable=True, comment='Количество'),
    sa.Column('amount_of_money', sa.Numeric(precision=10, scale=2), nullable=True, comment='Сумма'),
    sa.Column('remains', sa.Numeric(precision=10, scale=2), nullable=True, comment='Остаток'),
    sa.Column('debt', sa.Numeric(precision=10, scale=2), nullable=True, comment='Задолженность'),
    sa.ForeignKeyConstraint(['fk_id_product'], ['product.id_product'], name='fk_facts_product_id_product', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_facts_id'),
    comment='Факты'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facts')
    # ### end Alembic commands ###
