"""Add indexes to facts

Revision ID: 3e14513f0b79
Revises: 7bfc7199f965
Create Date: 2025-10-05 21:58:38.936803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e14513f0b79'
down_revision: Union[str, Sequence[str], None] = '7bfc7199f965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_facts_city', 'facts', ['fk_id_city'], unique=False)
    op.create_index('ix_facts_customer', 'facts', ['fk_id_customer'], unique=False)
    op.create_index('ix_facts_date', 'facts', ['fk_id_date'], unique=False)
    op.create_index('ix_facts_product', 'facts', ['fk_id_product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_facts_product', table_name='facts')
    op.drop_index('ix_facts_date', table_name='facts')
    op.drop_index('ix_facts_customer', table_name='facts')
    op.drop_index('ix_facts_city', table_name='facts')
    # ### end Alembic commands ###
