"""Add Table Localization

Revision ID: 656364ae38d4
Revises: 7ae422df3ebe
Create Date: 2025-10-04 21:25:09.532926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656364ae38d4'
down_revision: Union[str, Sequence[str], None] = '7ae422df3ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localization',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id локализации'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Тип локализации'),
    sa.PrimaryKeyConstraint('id', name='pk_localization_id'),
    comment='Локализация покупателя'
    )
    op.create_index('ix_localization_name', 'localization', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_localization_name', table_name='localization')
    op.drop_table('localization')
    # ### end Alembic commands ###
