"""Add Table City

Revision ID: 7ae422df3ebe
Revises: 1982bc15e86e
Create Date: 2025-10-04 21:12:41.021969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae422df3ebe'
down_revision: Union[str, Sequence[str], None] = '1982bc15e86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование'),
    sa.PrimaryKeyConstraint('id', name='pk_city_type_id'),
    comment='Тип'
    )
    op.create_index('ix_city_type_name', 'city_type', ['name'], unique=True)
    op.create_table('city',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fk_city_type_id', sa.UUID(), nullable=True, comment='FK Тип города'),
    sa.Column('city', sa.String(length=50), nullable=False, comment='Город'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Комментарий'),
    sa.ForeignKeyConstraint(['fk_city_type_id'], ['city_type.id'], name='city_fk_city_type_id_city_type_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_city_id'),
    comment='Город'
    )
    op.create_index('ix_city_city', 'city', ['city'], unique=False)
    op.create_foreign_key('fk_facts_city_id', 'facts', 'city', ['fk_id_city'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_facts_city_id', 'facts', type_='foreignkey')
    op.drop_index('ix_city_city', table_name='city')
    op.drop_table('city')
    op.drop_index('ix_city_type_name', table_name='city_type')
    op.drop_table('city_type')
    # ### end Alembic commands ###
