"""Add Table Customer

Revision ID: 7bfc7199f965
Revises: 656364ae38d4
Create Date: 2025-10-04 21:52:20.146962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfc7199f965'
down_revision: Union[str, Sequence[str], None] = '656364ae38d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False, comment='Id покупателя'),
    sa.Column('fk_localization_id', sa.UUID(), nullable=True, comment='FK ID локализации'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='Покупатель название'),
    sa.Column('address', sa.String(length=50), nullable=True, comment='Адрес'),
    sa.Column('contact', sa.String(length=50), nullable=True, comment='Контактное лицо'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='контектный телефон'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='почта'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Комментарий'),
    sa.ForeignKeyConstraint(['fk_localization_id'], ['localization.id'], name='fk_customer_localization_id', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_customer_id'),
    sa.UniqueConstraint('email', 'phone', name='uq_customer__email_phone'),
    comment='Покупатель'
    )
    op.create_index('ix_customer_address', 'customer', ['address'], unique=False)
    op.create_index('ix_customer_contact', 'customer', ['contact'], unique=False)
    op.create_index('ix_customer_name', 'customer', ['name'], unique=False)
    op.create_foreign_key('fk_facts_customer_id', 'facts', 'customer', ['fk_id_customer'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_facts_customer_id', 'facts', type_='foreignkey')
    op.drop_index('ix_customer_name', table_name='customer')
    op.drop_index('ix_customer_contact', table_name='customer')
    op.drop_index('ix_customer_address', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
