"""Init Tables pruduct and product_group

Revision ID: b4fd7e6d6a6b
Revises: 
Create Date: 2025-10-04 12:17:31.072572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fd7e6d6a6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_group',
    sa.Column('id_product_group', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Комментарий'),
    sa.PrimaryKeyConstraint('id_product_group', name='pk_product_group_id_product_group'),
    comment='Группа товаров'
    )
    op.create_index('ix_product_group_name', 'product_group', ['name'], unique=True)
    op.create_table('product',
    sa.Column('id_product', sa.UUID(), nullable=False),
    sa.Column('fk_product_group', sa.UUID(), nullable=True, comment='FK Гр Товаров'),
    sa.Column('id_catalog', sa.Integer(), nullable=True, comment='ID каталог'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='Наименование'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Комментарий'),
    sa.ForeignKeyConstraint(['id_product'], ['product_group.id_product_group'], name='fk_id_product_id_product_group', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_product', name='pk_model_thresholds_threshold_id')
    )
    op.create_index('ix_product_name', 'product', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_name', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_product_group_name', table_name='product_group')
    op.drop_table('product_group')
    # ### end Alembic commands ###
